### ISSUE TITLE
Reference project sdk versions instead of static ones

### ISSUE THREAD

**Issue by A1Jan** [urbanairship/capacitor-airship#23]
Inside https://github.com/urbanairship/capacitor-airship/blob/main/android/build.gradle#L30 the sdk versions like minSdkVersion and targetSdkVersion are referenced with static values. This should be changed like here (official capacitor plugin):
https://github.com/ionic-team/capacitor-plugins/blob/main/app/android/build.gradle

This will reference the project values and just set fallbacks.

Currently we cant build our project, because the main project is set to minSdk 24, which is incompatible with version 22 which is set statically in this plugin.

**Comment by rlepinski** [comment]
👍  Should be fine and a quick change to make. I might be able to get to it tomorrow but it may not happen til next week

**Comment by rlepinski** [comment]
Released in 3.0.1
