### ISSUE TITLE
When trying to start live activity, I get the error "Setup not called"

### ISSUE THREAD

**Issue by dheerajkumarsqm** [urbanairship/capacitor-airship#28]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
"@ua/capacitor-airship": "^3.1.0",
pod 'AirshipServiceExtension'
pod 'Airship'
pod 'Airship/Core'
pod 'Airship/MessageCenter'
pod 'Airship/Automation'
pod 'Airship/FeatureFlags'

### What are the versions of any relevant development tools you are using?
Xcode Version - 16.1

# Report

### What unexpected behavior are you seeing?
When try to start live activity then getting this error.
let startLive = await Airship.iOS.liveActivityManager.start({
    attributesType: "SportsActivityAttributes",
    content: {
      state: {
        status: "Game Pending",
      },
      relevanceScore: 0.0,
    },
    attributes: {
      gameID: "sports-game-123",
    },
  });
{errorMessage: "Setup not called", message: "Setup not called"}

### What is the expected behavior?
Push notifications work fine, but live activity does not.
I am following this documentation. 
https://docs.airship.com/platform/mobile/ios-live-activities/?groupid=capacitor#live-activities-overview

**Comment by rlepinski** [comment]
That error message is not as descriptive as it should be and we can update it in the future. What it means though is that the setup call is not happening that is outlined here - https://docs.airship.com/platform/mobile/ios-live-activities/?groupid=capacitor#app-setup

Can you share that file? Also, make sure that file is included in the target for the main app. Here is what it looks like in our sample:

![Screenshot 2024-12-11 at 7 53 06 AM](https://github.com/user-attachments/assets/fa81bfa4-7d7e-431a-91d5-1b476ff24fa0)

The target membership is in the right pane.

**Comment by rlepinski** [comment]
Were you able to resolve the issue?

**Comment by dheerajkumarsqm** [comment]
Yes, I was able to solve the issue. 
Thank you so much.
